#!/usr/bin/env node
/**
 * Volume 15 — Deployment helper.
 * Yeh script terminal me Firebase (aur optional AI) keys ek-ek karke poochta hai
 * aur khud ".env" file bana deta hai — taaki manually file edit na karni pade.
 *
 * Chalane ka tarika:
 *   npm run setup
 */
const readline = require("readline");
const fs = require("fs");
const path = require("path");

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(question) {
  return new Promise((resolve) => rl.question(question, resolve));
}

async function main() {
  console.log("\n=== AI Design Platform — Setup ===\n");
  console.log("Firebase Console (console.firebase.google.com) → Project Settings → Your apps");
  console.log("se yeh 6 values copy karke yahan paste karein.\n");
  console.log("(Agar abhi nahi pata, khaali chhod ke Enter dabayein — baad me .env file me daal sakte hain)\n");

  const firebaseApiKey = await ask("VITE_FIREBASE_API_KEY: ");
  const firebaseAuthDomain = await ask("VITE_FIREBASE_AUTH_DOMAIN: ");
  const firebaseProjectId = await ask("VITE_FIREBASE_PROJECT_ID: ");
  const firebaseStorageBucket = await ask("VITE_FIREBASE_STORAGE_BUCKET: ");
  const firebaseMessagingSenderId = await ask("VITE_FIREBASE_MESSAGING_SENDER_ID: ");
  const firebaseAppId = await ask("VITE_FIREBASE_APP_ID: ");

  console.log("\n--- Optional AI keys (bina inke bhi project chalega, sirf woh 3 AI features disabled rahenge) ---\n");
  const removeBgKey = await ask("VITE_REMOVE_BG_API_KEY (Enter to skip): ");
  const clipdropKey = await ask("VITE_CLIPDROP_API_KEY (Enter to skip): ");
  const openaiKey = await ask("VITE_OPENAI_API_KEY (Enter to skip): ");
  const adminEmails = await ask("VITE_ADMIN_EMAILS — comma se alag emails jo /admin khol sakein (Enter to skip): ");

  const envContent = `# Auto-generated by scripts/setup-env.js — is file ko kahin share na karein

VITE_FIREBASE_API_KEY=${firebaseApiKey}
VITE_FIREBASE_AUTH_DOMAIN=${firebaseAuthDomain}
VITE_FIREBASE_PROJECT_ID=${firebaseProjectId}
VITE_FIREBASE_STORAGE_BUCKET=${firebaseStorageBucket}
VITE_FIREBASE_MESSAGING_SENDER_ID=${firebaseMessagingSenderId}
VITE_FIREBASE_APP_ID=${firebaseAppId}

VITE_REMOVE_BG_API_KEY=${removeBgKey}
VITE_CLIPDROP_API_KEY=${clipdropKey}
VITE_OPENAI_API_KEY=${openaiKey}

VITE_ADMIN_EMAILS=${adminEmails}
`;

  const envPath = path.join(process.cwd(), ".env");
  fs.writeFileSync(envPath, envContent);

  console.log(`\n✅ .env file ban gayi: ${envPath}`);
  console.log("Ab yeh chalayein:\n  npm install\n  npm run dev\n");
  rl.close();
}

main();
